apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-with-volume
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nginxdemos/hello
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data-volume
          mountPath: /usr/share/nginx/html
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: ENV
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: PASSWORD
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: example-pvc 