apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - port: 80          # Puerto del servicio
      targetPort: 80    # Puerto del contenedor
      nodePort: 30007   # Puerto expuesto al exterior 